### ISSUE TITLE
Running initial migration FAILS

### ISSUE THREAD

**Issue by G00sfraba** [matthewbdaly/laravel-comments#1]
Running php artisan migrate after installation of this pack is resulting in the following Error:

In Connection.php line 664:
                                                                               
```
  SQLSTATE[HY000]: General error: 1005 Can't create table `semy-moodle`.`#sql  
  -a04_265` (errno: 150 "Foreign key constraint is incorrectly formed") (SQL:  
   alter table `comment_flags` add constraint `comment_flags_comment_id_forei  
  gn` foreign key (`comment_id`) references `comments` (`id`) on delete casca  
  de)       
```                                                                   
                                                                               

In PDOStatement.php line 107:
                                                                               
```
  SQLSTATE[HY000]: General error: 1005 Can't create table `semy-moodle`.`#sql  
  -a04_265` (errno: 150 "Foreign key constraint is incorrectly formed")        
                                                                               

```
In PDOStatement.php line 105:
                                                                               
```
  SQLSTATE[HY000]: General error: 1005 Can't create table `semy-moodle`.`#sql  
  -a04_265` (errno: 150 "Foreign key constraint is incorrectly formed")        
             
```                                                                  

The working set this was tried on was:
Laravel 5.5.39
PHP 7.0
DB: 10.1.21-MariaDB
With this bit here inside **AppServiceProvider.php** :
```
public function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by G00sfraba** [comment]
In **2017_12_29_184856_create_comment_flags_table**
Changing 
` $table->integer('comment_id');`
to
` $table->integer('comment_id')->unsigned();`

Fixed it.

**Comment by matthewbdaly** [comment]
Ok, do you want to submit a pull request for that? I'll create a new release this afternoon.

**Comment by G00sfraba** [comment]
Nah :) no time for that. Just add those 13 chars :)
