### ISSUE TITLE
Target [Matthewbdaly\LaravelComments\Contracts\Repositories\Comment] is not instantiable while building [\Matthewbdaly\LaravelComments\Http\Controllers\CommentController].

### ISSUE THREAD

**Issue by maiskiykot** [matthewbdaly/laravel-comments#2]
I tried use your package with Laravel/Lumen 6. After trying "Submit" comment I have fatal error message about not instantiable class. How I can fix it? I think - this little problem for author. But this big problem for me. Thank you!

**Comment by matthewbdaly** [comment]
I'll need to see the full error and stack trace to investigate this.

**Comment by maiskiykot** [comment]
[https__error.pdf](https://github.com/matthewbdaly/laravel-comments/files/5615693/https__error.pdf)

**Comment by matthewbdaly** [comment]
That sounds like the service provider isn't being loaded correctly, since that's where it sets a class to resolve that interface to.

That could be an issue with your configuration, or the service provider could be throwing an error. Please check that you can resolve the interface out of the container using Tinker, and try setting a breakpoint in the service provider using PsySh to see if that's running.

**Comment by maiskiykot** [comment]
I register provider 
$app->register(\Matthewbdaly\LaravelRepositories\Providers\LaravelRepositoriesServiceProvider::class);
And I tried bind controller and repository in bootstrap. After this I have continues animation "loading.gif" and nothing.

**Comment by matthewbdaly** [comment]
That's the provider for the repository package, not this one. For Lumen you will need to register both as it doesn't autoregister them like Laravel does.

**Comment by maiskiykot** [comment]
What is it both? What second provider?

**Comment by matthewbdaly** [comment]
This package has one service provider at https://github.com/matthewbdaly/laravel-comments/blob/master/src/Providers/CommentServiceProvider.php which you need to register. The one you've registered is for the repositories package which this depends on.

**Comment by maiskiykot** [comment]
Yes, I registered provider and go in controller. Please add registration of providers to your help.  Thank you!

**Comment by matthewbdaly** [comment]
To be honest, this package isn't a good fit for most Lumen applications and I'd be loath to recommend doing so. It's loosely inspired by Django's comments package, which is intended for more traditional web apps, not microservices.

Also, this package has never supported any version of Laravel that doesn't support automatic registration of service providers. Given the tiny window of usefulness for this in Lumen and the fact it's completely unnecessary in Laravel I don't think it makes much sense to document this.
